---
name: kate
version: 17.08.1
summary: KDE Advanced Text Editor
description: |-
    Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some preliminary scripting support.

    Features:

    - MDI, window splitting, window tabbing
    - Spell checking
    - CR, CRLF, LF newline support
    - Encoding support (utf-8, utf-16, ascii etc.)
    - Encoding conversion
    - Regular expression based find & replace
    - Powerful syntax highlighting and bracket matching
    - Code and text folding
    - Infinite undo/redo support
    - Block selection mode
    - Auto indentation
    - Auto completion support
    - Shell integration
    - Wide protocol support (http, ftp, ssh, webdav etc.) using kioslaves
    - Plugin architecture for the application and editor component
    - Customizable shortcuts
    - Integrated command line
    - Scriptable using JavaScript
confinement: strict
grade: stable
apps:
    kate:
        command: kf5-launch kate
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kate
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kate:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libgit2-dev
        - pkg-config
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kate-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
