#!/bin/sh

xvfb-run -a --server-args="-screen 0 1024x768x24" \
    Xephyr -reset -br -screen 1024x768 :2 & x_pid=$!

DISPLAY=:2 dbus-launch --exit-with-session debian/tests/testsuite.xsession
ret=$?
kill ${x_pid}
exit $ret
